// <auto-generated />
using System;
using DataMatrixCase.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataMatrixCase.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240929144150_InitialCreated")]
    partial class InitialCreated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataMatrix.Domain.Entities.DataMatrixInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("DecodedData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("decoded_data");

                    b.Property<string>("EncodingFormat")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("encoding_format");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("nvarchar")
                        .HasColumnName("metadata");

                    b.Property<DateTime>("ScanTimestamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("scan_timestamp");

                    b.Property<string>("SourceDeviceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("source_device_id");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("source_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("datamatrix_info");
                });
#pragma warning restore 612, 618
        }
    }
}
